AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'

  Exclude:
    - 'app/uploaders/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/*_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    # - !ruby/regexp /myfiles\.rb$/

  DisplayCopNames: true
  StyleGuideCopsOnly: false

Rails:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

# Metrics/PerceivedComplexity:
#   Max: 8

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

# Style/ClassAndModuleChildren:
#   Enabled: false

Style/StringLiterals:
  Enabled: false 

Style/FrozenStringLiteralComment:
  Enabled: false  

Style/EmptyLinesAroundBlockBody:  
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
